### PR TITLE
Names internationalization

### PR DESCRIPTION
**Pull request by flaviolivolsi**
Introducing first names and last names internationalization adding italian data and setting the existing data as english

```javascript
chance.name({ gender: "male", nationality: "en" }
// => 'Ryan McCormick'
chance.name({ gender: "female", nationality: "en" }
// => 'Duane Cox'
chance.name({ gender: "male", nationality: "it" }
// => 'Marco Ricci'
chance.name({ gender: "female", nationality: "it" }
// => 'Giulia Ferrari'
```

### CODE REVIEW

**Comment by victorquinn** [comment]
Nice addition, however for some reason there is something funny about your first commit because it marks the entire file, all 2400 lines, as changed.

Any way you could try to re-submit this PR without changing that whole file? I'm not sure what happened there but I'd really not like to lose the whole blame and diff history for the main file.

**Comment by flaviolivolsi** [comment]
@victorquinn whoops... you're right! I didn't notice it. It's probably issued caused by an automatic change of indentation style... I'll check and update you soon :)

**Comment by flaviolivolsi** [comment]
Nothing to do, I'm going to submit a new PR!

**Comment by victorquinn** [comment]
Closing since #211 is solving the same issue in a better, less breaking manner.

**Pull request closed without merging**
