### PR TITLE
Implemented chance.nationality

### PR DESCRIPTION
**Pull request by winkerxiao**
From issue #229

Used JSON from https://github.com/samsargent/Useful-Autocomplete-Data/blob/master/data/nationalities.json

-Open source
-Tested

### CODE REVIEW

**Comment by victorquinn** [comment]
Awesome, looking great, thanks for the contribution!

**Comment by winkerxiao** [comment]
This is my first pull request! Here are some screen shots from my tests

screen shot 2016-02-15 at 12 00 04 pm

**Comment by victorquinn** [comment]
And congrats on your first pull request @winkerxiao !

**Comment by winkerxiao** [comment]
Thanks @victorquinn!

**Pull request merged**
