### PR TITLE
AminaG. Create a valid Israel ID

### PR DESCRIPTION
**Pull request by AminaG**
AminaG. Create a valid Israel ID.

I have create the function, and the tests.
You can also test it here:
http://www.flex.co.il/Calculators/%D7%9E%D7%97%D7%A9%D7%91%D7%95%D7%9F-%D7%A1%D7%A4%D7%A8%D7%AA-%D7%91%D7%99%D7%A7%D7%95%D7%A8%D7%AA-%D7%AA%D7%A2%D7%95%D7%93%D7%AA-%D7%96%D7%94%D7%95%D7%AA.aspx

### CODE REVIEW

**Comment by AminaG** [comment]
I am fixing the Failed test (missing semicolons)

**Comment by AminaG** [comment]
This is ready to be merged.
Thank you :)

**Comment by somejeff** [comment]
I wonder if we should take this opportunity to create a more robust method. 

For example, instead of: israelID, cpf, ssn, sin, rut...
Have chance.citizenshipID({"country":"IL"});

**Comment by AminaG** [comment]
I think that we don't have enough countries yet. Let's merge this, and when we have at least 4 countries we can make the chance.citizenshipID metho.

**Comment by victorquinn** [comment]
Thanks!!

As I've mentioned in other issues, we need a better localization strategy both for getting data (like @somejeff suggests) and for making the library small for the browser when a developer doesn't need all of these localized I'd generators and just wants lightweight Chance.

**Pull request merged**
