### PR TITLE
Add md5() and avatar() methods

### PR DESCRIPTION
**Pull request by n8io**
Include a way to easily generate md5 hashes and (gr)avatar urls.

Sample usage:

```javascript
// md5()
chance.md5(); // = <random hash>
chance.md5('value'); // = 2063c1608d6e0baf80249c42e2be5804

// md5() w/all options
chance.md5({ str: 'value', key: 'key', raw: true }); // = 'C>ý_2~¤³DW,gö

// avatar()
chance.avatar(); // = //www.gravatar.com/avatar/<random hash>
chance.avatar('email@test.com'); // = //www.gravatar.com/avatar/f1f97cfa813c828a73528989da671a81

// avatar() w/all options
chance.avatar({
  email: 'email@test.com', 
  protocol: 'https', // http or https. Otherwise client determinate.
  fileExtension: 'png', // bmp, gif, or jpg. Otherwise no specification.
  rating: 'g', // g, pg, r, or x. Otherwise no specification.
  fallback: 'retro', // 404, mm, identicon, monsterid, wavatar, retro, or blank. Otherwise no specification.
  size: 80 // Integer determining the height and width. Must be positive.
}); // = https://www.gravatar.com/avatar/f1f97cfa813c828a73528989da671a81.png?&r=g&d=retro&s=80
```

### CODE REVIEW

**Comment by n8io** [comment]
@victorquinn I am having a hard time discovering what exactly failed on CI build so I can fix it. Any insight?

**Comment by victorquinn** [comment]
@n8io not really!

I see it passed on Node 0.12 and iojs, just failing on 0.10 and it didn't look like any substantive failure, looked like something early in the build process.

I tried restarting it in Travis but it's been queued and not building for a couple hours. I think everything will be alright if I can get it to run again.

**Comment by victorquinn** [comment]
See, it fixed itself! Thanks @n8io nice additions

**Comment by n8io** [comment]
Thanks @victorquinn! Glad you like the additions. What is the normal process and timing of moving these sorts of merges to the master branch?

**Comment by victorquinn** [comment]
Me cutting a release, which I just did. Should be live on npm as 0.7.5 momentarily.

**Pull request merged**
