### PR TITLE
Calculate the probability of a test failing

### PR DESCRIPTION
**Pull request by BlaMaeda**
The reasoning and code to compute the probability is here:
https://gist.github.com/BlaMaeda/cfd886f84dd093cb2ead

### CODE REVIEW

**Comment by victorquinn** [comment]
Love it, this is fantastic!

Would you mind updating your comment to include a link to your gist? Then I'll merge it in.

**Comment by BlaMaeda** [comment]
Done!

**Comment by victorquinn** [comment]
Thanks!

**Comment by BlaMaeda** [comment]
Thank you for the awesome library :)

**Pull request merged**
